name: Build

on:
  push:
    branches: master
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v1
      with:
       node-version: '10.x'
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Install Python dependencies
      run: |
        python -m pip install jupyterlab
        python -m pip install -r requirements.txt
    - name: Run Pytest
      run: pytest rucio_jupyterlab/tests/
    - name: Run Pylint
      run: pylint-fail-under --fail_under 8.5 rucio_jupyterlab/
    - name: Install JS dependencies
      run: jlpm
    - name: Run ESLint
      run: jlpm run eslint:check
    - name: Run Jest
      run: jlpm jest
    - name: Build the extension
      run: |
        pip install .
        jupyter lab build
        jupyter serverextension list 1>serverextensions 2>&1
        cat serverextensions | grep "rucio_jupyterlab.*OK"
        jupyter labextension list 1>labextensions 2>&1
        cat labextensions | grep "rucio-jupyterlab.*OK"

        python -m jupyterlab.browser_check
